### ISSUE TITLE
Differing location of libprotobuf

### ISSUE THREAD

**Issue by kazats** [openfoxwq/openfoxwq_qtclient#1]
I'm unfamiliar with qmake but on Arch Linux I had to change `/usr/local/lib/libprotobuf.a` to `/usr/lib/libprotobuf.so` in the Makefile for it to compile. (I'm assuming changing it in `openfoxwq_qtclient.pro` before running qmake would've been the proper way to do it?)

**Comment by ale64bit** [comment]
hey, thanks for reporting :)

> I'm assuming changing it in openfoxwq_qtclient.pro before running qmake would've been the proper way to do it?

I'm also not very familiar with qmake to be honest. I think there should be a way to change it in the .pro file so that it works more generally. But I'm not sure about the specifics of Qt and `LD_LIBRARY_PATH`. I need to look into it, since I don't have an Arch system to test.

How did you install the protobuf compiler and library?

**Comment by kazats** [comment]
> How did you install the protobuf compiler and library?

From the official repository: https://archlinux.org/packages/extra/x86_64/protobuf

**Comment by ale64bit** [comment]
Did the problem persist after the recent changes to the .pro file?

**Comment by kazats** [comment]
Works fine now 👍
