### ISSUE TITLE
"Find user" crashes client and server on players of some countries

### ISSUE THREAD

**Issue by kazats** [openfoxwq/openfoxwq_qtclient#2]
I found that when I search for players of some countries, the client and server both crash without showing the player profile.

[client.log](https://github.com/openfoxwq/openfoxwq_qtclient/files/10609595/client.log)
```
[...]
[libprotobuf ERROR /build/protobuf/src/protobuf-21.12/src/google/protobuf/message_lite.cc:133] Can't parse message of type "openfoxwq.WsResponse" because it is missing required fields: getPlayerInfo.register_info.country
ws: error parsing response
```

[server.log](https://github.com/openfoxwq/openfoxwq_qtclient/files/10609593/server.log):
```
[...]
2023/02/04 21:10:59 reading message: websocket: close 1006 (abnormal closure): unexpected EOF
```

I tried searching for a few accounts I found online and this happened for Germany (weiqidevil), Portugal (snakegame), and Bulgaria (zaraki17).
It didn't happen for China, Japan, South Korea, Taiwan, Macau (luis2356), Russia (zaraki15), and Great Britain (ypw61); these were shown normally.

**Comment by ale64bit** [comment]
Yes, there's a mention of it in the release notes. Thanks for reporting.
This happens because [not all countries](https://github.com/openfoxwq/openfoxwq/blob/main/proto/common.proto#L110) are mapped to their correct code. But it certainly shouldn't crash, just show "Unknown Country" at least. I'm not sure which mapping they are using (e.g. Canada's code is 11111 and so on). Other codes match the call code.

I'll fix it tomorrow and add some mechanism to report unknown countries.

**Comment by ale64bit** [comment]
Also, the server "crash" is actually intended. When the client quits (normally or otherwise), it closes the websocket connection and the server quits as well when it detects this.

**Comment by ale64bit** [comment]
Should be fixed with https://github.com/openfoxwq/openfoxwq/commit/0cc6571fb576b543f798704de3b312b0ff688884 if you are building the server yourself.
I'll upload updated binaries tomorrow.

**Comment by ale64bit** [comment]
Should be fixed in latest pre-release binaries. The server logs also will contain lines like:
```
unknown country: name=$NICK code=$CODE
```
with info about a missing country entry which can be used to add it to the recognized list.
